ManageabilityPkg: Declare variadic function with EFIAPI
HelperManageabilityDebugPrint() is a variadic function that is not
declared with EFIAPI, leading to a compiler failure when building with
CLANGDWARF:

  BaseManageabilityTransportHelper.c:462:3: error:
    '__builtin_ms_va_start' used in System V ABI function

While other functions in the header should also use EFIAPI, this
commit is making a minimal change to fix CI from failing for every
commit to master.

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>