CpuException: Init global variables in-place
(cherry picked from commit 34d505123e4e7690b29a0926949a1868c49f8b44)

Additionally removed two useless global variables:
"SPIN_LOCK  mDisplayMessageSpinLock" from SMM instance.
"UINTN mEnabledInterruptNum" from DXE instance.

Signed-off-by: Ray Ni <ray.ni@intel.com>
Cc: Eric Dong <eric.dong@intel.com>
(cherry picked from commit 34d505123e4e7690b29a0926949a1868c49f8b44)

Change-Id: I96f26c6fea8a185ad19a09fbba8e091c19724dd2