CpuException: Avoid allocating page but using global variables
(cherry picked from commit 2fbc5ff0a517b73aecf26ece6a040f265d878f81)

Signed-off-by: Ray Ni <ray.ni@intel.com>
Cc: Eric Dong <eric.dong@intel.com>
(cherry picked from commit 2fbc5ff0a517b73aecf26ece6a040f265d878f81)

Change-Id: I664bcdac9532df5ff8bfd9679727e7b68ddad718