CryptoPkg/OpensslLib: Fix GCC unused-value warnings with HOST_c2l() (RT#4347)
If we actually allow GCC to produce warnings, we'll see a lot of these:
…/crypto/md5/md5_dgst.c:109:56: error: right-hand operand of comma expression has no effect [-Werror=unused-value]

These were fixed in OpenSSL 1.1; backport the fix to our 1.0.2 tree too.

Contributed-under: TianoCore Contribution Agreement 1.0
Signed-off-by: David Woodhouse <David.Woodhouse@intel.com>