StandaloneMmPkg/StandaloneMmCore: Fix compiler warning
(cherry picked from commit 1d27e58e401faea284309039f3962cb3cb4549fc)

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3204

Fixes the following compiler warning in VS2019 by changing defining
the MmramRangeCount variable to be UINTN and type casting prior
to value assignment.

\edk2\StandaloneMmPkg\Core\StandaloneMmCore.c(570): error C2220:
  the following warning is treated as an error
\edk2\StandaloneMmPkg\Core\StandaloneMmCore.c(570): warning C4244:
  '=': conversion from 'UINT64' to 'UINT32', possible loss of data

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>
Reviewed-by: Sami Mujawar <sami.mujawar@arm.com>
(cherry picked from commit 1d27e58e401faea284309039f3962cb3cb4549fc)

Change-Id: I61e960e9ba06cb30acb1b094e43b1f186b8cb06f