IntelFsp2Pkg/Tools: Fix a typo issue
(cherry picked from commit 29d14d3a30fdfbe017d39b759423832054280f10)

Error message:
raise Exception ("'%s' is not a valid directory!" % FvDir)
NameError: name 'FvDir' is not defined

FvDir should be fvDir.

Cc: Chasel Chiu <chasel.chiu@intel.com>
Cc: Nate DeSimone <nathaniel.l.desimone@intel.com>
Cc: Star Zeng <star.zeng@intel.com>
Signed-off-by: Yunhua Feng <fengyunhua@byosoft.com.cn>
Reviewed-by: Chasel Chiu <chasel.chiu@intel.com>
Reviewed-by: Nate DeSimone <nathaniel.l.desimone@intel.com>
(cherry picked from commit 29d14d3a30fdfbe017d39b759423832054280f10)

Change-Id: Iad64f69ec23890f0e3d5fc612cdcbe6abc43ac66