OvmfPkg/Sec: Use correct prototype of ProcessLibraryConstructorList()
The prototype of ProcessLibraryConstructorList(), which is generated by
the build tools, depends on the boot phase, and SEC and PEI differ in
this regard. However, OVMF's SEC implemention includes PeimEntryPoint.h
and calls the PEI version of the protoype (passing NULL arguments),
whereas the actual implementation observed by the compiler follows the
SEC version, which takes VOID.

The compiler usually doesn't spot the difference, but the LTO linker
does, and throws an error:

MdePkg/Include/Library/PeimEntryPoint.h:74:1: error: type of 'ProcessLibraryConstructorList' does not match original declaration [-Werror=lto-type-mismatch]
   74 | ProcessLibraryConstructorList (
      | ^
Build/OvmfX64/RELEASE_GCC5/X64/OvmfPkg/Sec/SecMain/DEBUG/AutoGen.c:310:1: note: type mismatch in parameter 1
  310 | ProcessLibraryConstructorList (
      | ^
Build/OvmfX64/RELEASE_GCC5/X64/OvmfPkg/Sec/SecMain/DEBUG/AutoGen.c:310:1: note: type 'void' should match type 'void *'
Build/OvmfX64/RELEASE_GCC5/X64/OvmfPkg/Sec/SecMain/DEBUG/AutoGen.c:310:1: note: 'ProcessLibraryConstructorList' was previously declared here

Fix this by dropping the #include, and providing a declaration of
ProcessLibraryConstructorList() in SecMain.c

Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=4643
Signed-off-by: Ard Biesheuvel <ardb@kernel.org>
Message-Id: <20240202182455.1535328-1-ardb+git@google.com>
Cc: Ard Biesheuvel <ardb+tianocore@kernel.org>
Cc: Erdem Aktas <erdemaktas@google.com>
Cc: Gerd Hoffmann <kraxel@redhat.com>
Cc: Jiewen Yao <jiewen.yao@intel.com>
Cc: Michael Roth <michael.roth@amd.com>
Cc: Min Xu <min.m.xu@intel.com>
Cc: Tom Lendacky <thomas.lendacky@amd.com>
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=990
Signed-off-by: Laszlo Ersek <lersek@redhat.com>