MdeModulePkg: Remove unused variables
XCODE5 toolchain finds these, with errors such as:
SmbiosMeasurementDxe.c:221:10: error: variable 'Size' set but not used

Signed-off-by: Mike Beaton <mjsbeaton@gmail.com>