MdeModulePkg/UsbBusDxe: fix NOOPT build error
(cherry picked from commit ae8272ef787d80950803c521a13a308651bdc62e)

gcc-11 (fedora 35):

/home/kraxel/projects/edk2/MdeModulePkg/Bus/Usb/UsbBusDxe/UsbBus.c: In function ?UsbIoBulkTransfer?:
/home/kraxel/projects/edk2/MdeModulePkg/Bus/Usb/UsbBusDxe/UsbBus.c:277:12: error: ?UsbHcBulkTransfer? accessing 80 bytes in a region of size 8 [-Werror=stringop-overflow=]

Signed-off-by: Gerd Hoffmann <kraxel@redhat.com>
Reviewed-by: Hao A Wu <hao.a.wu@intel.com>
(cherry picked from commit ae8272ef787d80950803c521a13a308651bdc62e)

Change-Id: I99118e53a207adf4ebfa58864685c06872981bf1