CryptoPkg/OpensslLib: Fix build on current XCODE5
This fix uses a define which is already implemented in rand.h, and already takes effect on Apple only.

Without this change, we see:

In file included from /Users/mjsbeaton/OpenSource/edk2/CryptoPkg/Library/OpensslLib/OpensslStub/rand_pool.c:10:
/Users/mjsbeaton/OpenSource/edk2/CryptoPkg/Library/OpensslLib/openssl/include/crypto/rand.h:26:12: fatal error: 'Availability.h' file not found
#  include <Availability.h>
           ^~~~~~~~~~~~~~~~

Signed-off-by: Mike Beaton <mjsbeaton@gmail.com>