SignedCapsulePkg: fix AARCH64 build
(cherry picked from commit 0f28c513d392a807f7b4225964eba6e2b1c453a2)

BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2252

Add NULL library resolution of CompilerIntrinsicsLib and
BaseStackCheckLib for AARCH64 as well as ARM in order to
fix "undefined reference to `memcpy'" build errors.

Cc: Jiewen Yao <jiewen.yao@intel.com>
Cc: Chao Zhang <chao.b.zhang@intel.com>
Cc: Laszlo Ersek <lersek@redhat.com>
Signed-off-by: Leif Lindholm <leif.lindholm@linaro.org>
Reviewed-by: Jiewen Yao <Jiewen.yao@intel.com>
(cherry picked from commit 0f28c513d392a807f7b4225964eba6e2b1c453a2)