MdeModulePkg/UnicodeCollation: Fix uninitialized variable usage
Build failed with the below error:
error: variable 'Status' is used uninitialized when
PcdUnicodeCollation2Support is FALSE.

Fixing this issue by initializing Status unconditionally.

This is a regression issue caused by below Edk2 commit
a46697f73532dbaa84babacc887cd5ccd8c4fdc2

Signed-off-by: HemaAnmisha <hema.anmisha.kalavakolanu@intel.com>