MdeModulePkg: Fix build failure of uninitialized variable usage
Few builds failed with the below error:
error: variable 'Status' is used uninitialized whenever 'if'
condition is false.

Fixing this issue by initializing Status to EFI_SUCCESS.

This is a regression issue caused by below Edk2 commit
a46697f73532dbaa84babacc887cd5ccd8c4fdc2

Signed-off-by: HemaAnmisha <hema.anmisha.kalavakolanu@intel.com>