StandaloneMmPkg StandaloneMmCoreMemoryAllocationLib: Rename gMmst
StandaloneMmCoreMemoryAllocationLib.c and StandaloneMmServicesTableLib.c
are both defining gMmst, StandaloneMmCoreMemoryAllocationLib will be
linked to StandaloneMmCore directly, StandaloneMmServicesTableLib may be
linked to StandaloneMmCore indirectly, when they are both linked to
StandaloneMmCore, there will be "lld-link: error: duplicate symbol: gMmst"
build error with Clang compiler.

gMmst is declared in MmServicesTableLib.h and its definition should be
owned by MmServicesTableLib.

This patch renames gMmst in StandaloneMmCoreMemoryAllocationLib.c to
mMemoryAllocationMmst to avoid this build error.

Signed-off-by: Star Zeng <star.zeng@intel.com>