SecurityPkg: Remove unused variable
XCODE5 toolchain finds this, with error:
Tpm2Capability.c:535:23: error: variable 'ActivePcrBankCount' set but not used

Fixes: https://github.com/tianocore/edk2/commit/1f2adcbba571faead4795bfbeeb232e82166c901

Signed-off-by: Mike Beaton <mjsbeaton@gmail.com>