MdePkg: Fix DEBUG_CODE and PERF_CODE macros for XCODE5
Addresses https://bugzilla.tianocore.org/show_bug.cgi?id=3704

Without these changes, we get the error:

  error: variable '__DebugCodeLocal' set but not used

from the DebugLib.h DEBUG_CODE_BEGIN()/END() macros on XCODE5.

Similarly, in NOOPT builds only, we get:

  error: variable '__PerformanceCodeLocal' set but not used

from the PerformanceLib.h PERF_CODE_BEGIN()/END() macros on XCODE5.

The modified versions work on all toolchains.

The previous definitions of DEBUG_CODE_BEGIN() and DEBUG_CODE_END() use
the local variable __DebugCodeLocal as an attempt to track parity: if
DEBUG_CODE_END() is used without a preceding DEBUG_CODE_BEGIN(),
__DebugCodeLocal will not have been declared and a compilation error
will be issued. These mutations of the variable are not used to track
nesting or similar. As the value of this variable is never actually
used, recent Clang versions issue an "unused-but-set-variable" warning
for it.

To solve this, redefine __DebugCodeLocal as a BOOLEAN that is always
FALSE and use it in a do-while loop condition as done explicitly in
many places. As in the previous solution, DEBUG_CODE_END() cannot be
used without DEBUG_CODE_BEGIN(), as __DebugCodeLocal will be not have
been defined.

Also make the matching change in the PERF_CODE_BEGIN()/END() macros.

Signed-off-by: Marvin Häuser <mhaeuser@posteo.de>
Signed-off-by: Mikhail Krichanov <krichanov@ispras.ru>
Signed-off-by: Mike Beaton <mjsbeaton@gmail.com>